# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenTrack' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OpenTrack

  target 'OpenTrackTests' do
    inherit! :search_paths
    pod 'GoogleAPIClientForREST/Sheets', '~> 1.0.3'
    pod 'GTMOAuth2', '~> 1.1.2'
    # Pods for testing
  end

end
